ingress-nginx:
  controller:
    autoscaling:
      enabled: true
      maxReplicas: 2
      minReplicas: 1
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 90
    ingressClassResource:
      default: false
    service:
      type: LoadBalancer
    config:
      use-forwarded-headers:  false
      proxy-body-size: 100M
      proxy-buffer-size: 16k
    admissionWebhooks:
      enabled: false
    resources:
      requests:
        memory: 350Mi
        cpu: 200m
      limits:
        memory: 350Mi
        cpu: 500m
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
